name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 21.x
  #         cache: npm
  #     - run: npm ci
  #     - name: linting
  #       run: npm run lint
  #     - name: actual testing
  #       run: node RUN.TESTS.js

  # build-server:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: build and push a docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: server.Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/idg2671:latest

  # build-client:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: build and push a docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: client.Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/idg2671-client:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: [build-server, build-client]
    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding our prod server to known hosts
        run: ssh-keyscan -v -H ${{ secrets.DEPLOY_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Login with SSH, aka run deployment script on the server
        run: ssh -tt ${{secrets.DEPLOY_SSH_USERNAME}}@${{secrets.DEPLOY_SSH_HOST}}